export const userData = [
  {
    id: 2,
    profilePicture: require('../../assets/images/person/shar.png'),
    userName: 'Shahrukh khan',
    description: 'Har har mahadev',
    photo: require('../../assets/images/48499fc1-719a-4707-87cb-03848cfbb6ef.jpg'),
    date: '51 min',
    like: 100,
    Comment: 100,
    message: 'kyn kya huwa?',
  },
  {
    id: 3,
    profilePicture: require('../../assets/images/person/kun.png'),
    userName: 'Kundan Bhasin',
    description: 'Jai shri Ram',
    photo: require('../../assets/images/5419.jpg'),
    date: '1 hour',
    like: 100,
    Comment: 100,
    message: 'Where are you?',
  },
  {
    id: 4,
    profilePicture: require('../../assets/images/person/princ.png'),
    userName: 'Price rajbhar',
    description: 'Radhey Radhey',
    photo: require('../../assets/images/640969.jpg'),
    date: '20 min',
    like: 51,
    Comment: 41,
    message: 'Sent you Video',
  },
  {
    id: 5,
    profilePicture: require('../../assets/images/person/rajt.png'),
    userName: 'Rajat Mehta',
    description: 'Jai ho',
    photo: require('../../assets/images/7114.jpg'),
    date: '40 min',
    like: 44,
    Comment: 55,
    message: 'Sent you Audio',
  },
  {
    id: 6,
    profilePicture: require('../../assets/images/person/raju.png'),
    userName: 'Raju Bhai',
    description: 'Jai kali Mata',
    photo: require('../../assets/images/birth.jpg'),
    date: '1 days',
    like: 10,
    Comment: 10,
    message: 'jai ho',
  },
  {
    id: 7,
    profilePicture: require('../../assets/images/person/sal.png'),
    userName: 'salman',
    photo: require('../../assets/images/world.jpg'),
    date: '15 hour',
    like: 10,
    Comment: 10,
    message: 'Hello',
  },
  {
    id: 8,
    profilePicture: require('../../assets/images/person/rajpal_yadav.jpeg'),
    userName: 'Rajpal yadav',
    description: 'World tour',
    photo: require('../../assets/images/wallpaperflare.jpg'),
    date: '5 min',
    like: 10,
    Comment: 10,
    message: 'bye',
  },
  {
    id: 9,
    profilePicture: require('../../assets/images/person/Johny.jpg'),
    userName: 'Jonny Lever',
    photo: require('../../assets/images/IMG_20210925_174314.jpg'),
    date: '0 min',
    like: 0,
    Comment: 0,
    message: 'phir thik hai',
  },
  {
    id: 10,
    profilePicture: require('../../assets/images/person/vijay.jpeg'),
    userName: 'vijay Raaz',
    userId: 10,
    photo: require('../../assets/images/thiago-gomes-K0YuYMAwCTQ-unsplash.jpg'),
    date: '5 min',
    like: 10,
    Comment: 10,
    message: 'sb bekar hai',
  },
];
